"""
SGB Data Validator - Main entry point

This package validates and manages Omeka S data for the Stadt.Geschichte.Basel project.
For detailed usage information, see the documentation.
"""

import sys


def main() -> int:
    """Main entry point - displays usage information"""
    print("=" * 80)
    print("SGB DATA VALIDATOR")
    print("=" * 80)
    print()
    print("This package validates and manages Omeka S data for the")
    print("Stadt.Geschichte.Basel project.")
    print()
    print("=" * 80)
    print("AVAILABLE COMMANDS")
    print("=" * 80)
    print()
    print("1. VALIDATE - Validate data from Omeka S API")
    print("   uv run python validate.py --help")
    print()
    print("   Examples:")
    print("   # Validate with settings from .env file")
    print("   uv run python validate.py")
    print()
    print("   # Validate specific item set")
    print("   uv run python validate.py --item-set-id 10780")
    print()
    print("   # Check URIs and export CSV reports")
    print("   uv run python validate.py --check-uris --export-csv")
    print()
    print("   # Enable data profiling")
    print("   uv run python validate.py --profile")
    print()
    print("2. WORKFLOW - Download, transform, validate, and upload data")
    print("   uv run python workflow.py --help")
    print()
    print("   Examples:")
    print("   # Download raw data from Omeka S")
    print("   uv run python workflow.py download --item-set-id 10780")
    print()
    print("   # Transform downloaded data (apply whitespace normalization)")
    print("   uv run python workflow.py transform data/raw_itemset_10780_*/")
    print()
    print("   # Transform downloaded data (ALL transformations by default)")
    print("   uv run python workflow.py transform data/raw_itemset_10780_*/")
    print()
    print("   # Transform with only whitespace normalization")
    print(
        "   uv run python workflow.py transform data/raw_itemset_10780_*/ --no-all-transformations"
    )
    print()
    print("   # Validate offline files")
    print("   uv run python workflow.py validate data/transformed_itemset_10780_*/")
    print()
    print("   # Upload with dry-run (preview changes)")
    print("   uv run python workflow.py upload data/transformed_itemset_10780_*/")
    print()
    print("   # Upload for real (requires credentials)")
    print("   uv run python workflow.py upload data/transformed_itemset_10780_*/ \\")
    print("     --no-dry-run --base-url https://omeka.unibe.ch \\")
    print("     --key-identity YOUR_KEY --key-credential YOUR_SECRET")
    print()
    print("=" * 80)
    print("KEY FEATURES")
    print("=" * 80)
    print()
    print("✓ Schema validation using Pydantic models")
    print("✓ Controlled vocabularies (Era, MIME types, Licenses, Iconclass)")
    print("✓ ISO 639-1 language validation (all 184 two-letter codes)")
    print("✓ URI validation with reachability checks")
    print("✓ CSV reports for easy data quality review")
    print("✓ Data profiling with interactive HTML reports")
    print("✓ Data transformation with whitespace normalization")
    print("✓ Comprehensive transformations (Unicode NFC, HTML entities, etc.)")
    print("✓ Python API for programmatic access")
    print("✓ Offline workflow for safe batch updates")
    print()
    print("=" * 80)
    print("CONFIGURATION")
    print("=" * 80)
    print()
    print("Create a .env file in the project root with:")
    print()
    print("  OMEKA_URL=https://omeka.unibe.ch")
    print("  KEY_IDENTITY=your_key_identity")
    print("  KEY_CREDENTIAL=your_key_credential")
    print("  ITEM_SET_ID=10780")
    print()
    print("Command-line parameters override .env values.")
    print()
    print("=" * 80)
    print("DOCUMENTATION")
    print("=" * 80)
    print()
    print("For more information, see:")
    print("  - README.md - Full documentation and examples")
    print("  - IMPLEMENTATION.md - Technical implementation details")
    print("  - examples/ - Code examples for API usage")
    print("  - https://Stadt-Geschichte-Basel.github.io/sgb-data-validator/")
    print()
    print("=" * 80)
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
