contact_links:
  - name: Are you looking for documentation on sgb-data-validator?
    url: https://Stadt-Geschichte-Basel.github.io/sgb-data-validator
    about: Please see the documentation for sgb-data-validator on its GitHub Pages page.
  - name: Do you want to discuss sgb-data-validator with the community?
    url: https://github.com/Stadt-Geschichte-Basel/sgb-data-validator/discussions
    about: Please see the discussions page for sgb-data-validator.
blank_issues_enabled: true
